cooldown: 500

messages:
  noDeath: '&c>> Последняя точка смерти не обнаружена!'
  teleport: '&e>> Вы были телепортированы на последнюю точку смерти!'
  noPerm: '&c>> У вас недостаточно прав!'
  reload: '&a>> Плагин успешно перезагружен!'
  cantTp: '&c>> Вы больше не можете телепортироваться на точку своей смерти!'
  cooldown: '&c>> Подождите %time% сек. перед повторным использованием команды!'